const createStand = ({ id, name, treeType, canopyDensity, ageClass, health, summary, management, lon, lat }) => ({
  type: "Feature",
  properties: {
    id,
    name,
    treeType,
    canopyDensity,
    ageClass,
    health,
    summary,
    management,
  },
  geometry: {
    type: "Polygon",
    coordinates: [
      [
        [lon - 0.25, lat + 0.18],
        [lon + 0.25, lat + 0.18],
        [lon + 0.25, lat - 0.18],
        [lon - 0.25, lat - 0.18],
        [lon - 0.25, lat + 0.18],
      ],
    ],
  },
});

export const treeStands = [
  createStand({
    id: "cedar-ridge",
    name: "Cedar Ridge",
    treeType: "Western Red Cedar",
    canopyDensity: 0.84,
    ageClass: "Mature",
    health: "Thriving",
    summary:
      "A dense coastal stand with layered canopies that shelter songbirds and moist-soil understory plants.",
    management: "Preserve the mature overstory and maintain seasonal monitoring.",
    lon: -123.15,
    lat: 45.55,
  }),
  createStand({
    id: "oak-hollow",
    name: "Oak Hollow",
    treeType: "White Oak",
    canopyDensity: 0.68,
    ageClass: "Mid-Successional",
    health: "Stable",
    summary:
      "A broadleaf stand with steady canopy closure and excellent habitat diversity for pollinators.",
    management: "Keep the understory open with periodic light thinning.",
    lon: -89.6,
    lat: 38.75,
  }),
  createStand({
    id: "pine-crest",
    name: "Pine Crest",
    treeType: "Loblolly Pine",
    canopyDensity: 0.78,
    ageClass: "Young Mature",
    health: "Healthy",
    summary:
      "A fast-growing conifer stand with strong canopy layering and moderate shade tolerance beneath.",
    management: "Use controlled burns on a long interval to reduce fuel buildup.",
    lon: -84.1,
    lat: 32.45,
  }),
  createStand({
    id: "spruce-plain",
    name: "Spruce Plain",
    treeType: "Engelmann Spruce",
    canopyDensity: 0.61,
    ageClass: "Overmature",
    health: "Watch",
    summary:
      "A high-elevation stand with scattered gaps where wind and snow have started to shape the canopy.",
    management: "Prioritize snag retention and low-impact access planning.",
    lon: -110.8,
    lat: 39.6,
  }),
  createStand({
    id: "maple-grove",
    name: "Maple Grove",
    treeType: "Sugar Maple",
    canopyDensity: 0.73,
    ageClass: "Established",
    health: "Excellent",
    summary:
      "A vibrant deciduous woodland with dense summer shade and strong fall color displays.",
    management: "Maintain a mosaic of canopy openings for regeneration pockets.",
    lon: -72.5,
    lat: 43.85,
  }),
  createStand({
    id: "fir-bend",
    name: "Fir Bend",
    treeType: "Douglas Fir",
    canopyDensity: 0.79,
    ageClass: "Mature",
    health: "Strong",
    summary: "A cool, shaded stand with rich understory growth and regular misting conditions.",
    management: "Protect the canopy edge and monitor for root disturbance.",
    lon: -122.9,
    lat: 45.2,
  }),
  createStand({
    id: "ash-valley",
    name: "Ash Valley",
    treeType: "Green Ash",
    canopyDensity: 0.66,
    ageClass: "Early Mature",
    health: "Stable",
    summary: "A river-adjacent woodland with moderate closure and excellent floodplain resilience.",
    management: "Maintain streamside buffers and inspect for pest pressure.",
    lon: -91.2,
    lat: 40.2,
  }),
  createStand({
    id: "beech-crest",
    name: "Beech Crest",
    treeType: "American Beech",
    canopyDensity: 0.74,
    ageClass: "Established",
    health: "Excellent",
    summary: "A smooth-crowned stand with thick leaf litter and supportive habitat for woodland fungi.",
    management: "Avoid heavy disturbance and retain fallen logs.",
    lon: -78.5,
    lat: 43.6,
  }),
  createStand({
    id: "hemlock-hollow",
    name: "Hemlock Hollow",
    treeType: "Eastern Hemlock",
    canopyDensity: 0.81,
    ageClass: "Mature",
    health: "Healthy",
    summary: "A shaded ravine stand that buffers cool air and supports moisture-loving species.",
    management: "Protect from invasive species and preserve stream adjacency.",
    lon: -75.8,
    lat: 44.2,
  }),
  createStand({
    id: "juniper-slope",
    name: "Juniper Slope",
    treeType: "Rocky Mountain Juniper",
    canopyDensity: 0.58,
    ageClass: "Young",
    health: "Watch",
    summary: "An open, drought-tolerant woodland with wide gaps between crowns and exposed rock.",
    management: "Prioritize water retention and reduce trampling pressure.",
    lon: -106.4,
    lat: 39.1,
  }),
  createStand({
    id: "walnut-plain",
    name: "Walnut Plain",
    treeType: "Black Walnut",
    canopyDensity: 0.72,
    ageClass: "Mid-Successional",
    health: "Strong",
    summary: "A productive upland stand with deep roots and healthy subcanopy development.",
    management: "Harvest carefully and keep regeneration plots distributed across the site.",
    lon: -86.4,
    lat: 37.8,
  }),
  createStand({
    id: "larch-ridge",
    name: "Larch Ridge",
    treeType: "Tamarack",
    canopyDensity: 0.69,
    ageClass: "Established",
    health: "Stable",
    summary: "A cool-climate stand with seasonal needle drop that supports a varied understory.",
    management: "Avoid drainage changes and continue long-term monitoring.",
    lon: -116.2,
    lat: 47.4,
  }),
  createStand({
    id: "cypress-bay",
    name: "Cypress Bay",
    treeType: "Bald Cypress",
    canopyDensity: 0.76,
    ageClass: "Mature",
    health: "Healthy",
    summary: "A swamp-edge stand with strong canopy layering and important wetland habitat features.",
    management: "Maintain water levels and preserve snags for wildlife.",
    lon: -90.1,
    lat: 29.7,
  }),
  createStand({
    id: "poplar-meadow",
    name: "Poplar Meadow",
    treeType: "Eastern Cottonwood",
    canopyDensity: 0.64,
    ageClass: "Young Mature",
    health: "Stable",
    summary: "A fast-growing stand with open structure and wide light penetration near the ground.",
    management: "Balance growth with periodic canopy opening and regeneration efforts.",
    lon: -95.5,
    lat: 42.9,
  }),
  createStand({
    id: "elm-glade",
    name: "Elm Glade",
    treeType: "American Elm",
    canopyDensity: 0.71,
    ageClass: "Established",
    health: "Watch",
    summary: "A broad, airy stand with high cultural value and moderate disease pressure.",
    management: "Retain resistant individuals and diversify future plantings.",
    lon: -87.9,
    lat: 41.8,
  }),
  createStand({
    id: "fir-landing",
    name: "Fir Landing",
    treeType: "Grand Fir",
    canopyDensity: 0.83,
    ageClass: "Mature",
    health: "Thriving",
    summary: "A dense montane stand with excellent vertical canopy structure and cold-air capture.",
    management: "Protect the interior core and limit disturbance at the margins.",
    lon: -121.3,
    lat: 46.8,
  }),
  createStand({
    id: "sycamore-park",
    name: "Sycamore Park",
    treeType: "American Sycamore",
    canopyDensity: 0.67,
    ageClass: "Mid-Successional",
    health: "Healthy",
    summary: "A wide-canopied stand that cools nearby trails and supports strong urban habitat value.",
    management: "Maintain pruning cycles and preserve mature limbs.",
    lon: -80.3,
    lat: 35.7,
  }),
  createStand({
    id: "alder-brook",
    name: "Alder Brook",
    treeType: "Red Alder",
    canopyDensity: 0.62,
    ageClass: "Young",
    health: "Stable",
    summary: "A moist lowland stand with layered shrubs and active regeneration along the stream.",
    management: "Keep streambanks intact and watch for invasive plants.",
    lon: -123.8,
    lat: 44.9,
  }),
  createStand({
    id: "pine-echo",
    name: "Pine Echo",
    treeType: "Longleaf Pine",
    canopyDensity: 0.77,
    ageClass: "Established",
    health: "Strong",
    summary: "An open, fire-adapted stand with high biodiversity in the herbaceous layer.",
    management: "Continue prescribed fire planning and keep fuels low.",
    lon: -84.8,
    lat: 31.4,
  }),
  createStand({
    id: "birch-bloom",
    name: "Birch Bloom",
    treeType: "Paper Birch",
    canopyDensity: 0.59,
    ageClass: "Young Mature",
    health: "Watch",
    summary: "A bright, light-filled stand that is recovering from earlier stress and canopy loss.",
    management: "Favor resilient regeneration and reduce compacted access routes.",
    lon: -71.4,
    lat: 44.7,
  }),
  createStand({
    id: "cedar-lake",
    name: "Cedar Lake",
    treeType: "Northern White Cedar",
    canopyDensity: 0.75,
    ageClass: "Mature",
    health: "Healthy",
    summary: "A wetland-adjacent stand with strong structure and high resilience to seasonal flooding.",
    management: "Preserve hydrology and maintain protective buffers.",
    lon: -92.5,
    lat: 46.7,
  }),
  createStand({
    id: "hickory-dale",
    name: "Hickory Dale",
    treeType: "Bitternut Hickory",
    canopyDensity: 0.70,
    ageClass: "Established",
    health: "Strong",
    summary: "A well-developed upland stand with a diverse mix of canopy and understory layers.",
    management: "Retain a mix of age classes and monitor deer browse.",
    lon: -83.3,
    lat: 40.8,
  }),
  createStand({
    id: "madrone-hill",
    name: "Madrone Hill",
    treeType: "Pacific Madrone",
    canopyDensity: 0.65,
    ageClass: "Mid-Successional",
    health: "Stable",
    summary: "A sunny, dry slope stand with excellent seasonal color and mixed shrub cover.",
    management: "Limit invasive spread and retain shrub cover for cover.",
    lon: -123.5,
    lat: 38.4,
  }),
  createStand({
    id: "spruce-arc",
    name: "Spruce Arc",
    treeType: "Blue Spruce",
    canopyDensity: 0.82,
    ageClass: "Mature",
    health: "Thriving",
    summary: "A dense conifer stand with strong winter shelter and high visual cover.",
    management: "Protect the older stems and manage recreation traffic carefully.",
    lon: -105.8,
    lat: 40.5,
  }),
  createStand({
    id: "oak-crossing",
    name: "Oak Crossing",
    treeType: "Bur Oak",
    canopyDensity: 0.68,
    ageClass: "Overmature",
    health: "Watch",
    summary: "A broad, ancient stand with scattered gaps and high structural diversity.",
    management: "Favor structural retention and avoid over-thinning.",
    lon: -94.2,
    lat: 43.0,
  }),
  createStand({
    id: "chestnut-grove",
    name: "Chestnut Grove",
    treeType: "American Chestnut",
    canopyDensity: 0.73,
    ageClass: "Young Mature",
    health: "Healthy",
    summary: "A recovering stand with strong regeneration and steady canopy closure.",
    management: "Protect new sprouts and maintain a flexible monitoring plan.",
    lon: -79.6,
    lat: 37.0,
  }),
  createStand({
    id: "pine-harbor",
    name: "Pine Harbor",
    treeType: "Pitch Pine",
    canopyDensity: 0.60,
    ageClass: "Young",
    health: "Stable",
    summary: "A low, wind-exposed stand that balances open gaps with dense patches.",
    management: "Keep firebreaks clear and preserve habitat patches.",
    lon: -74.8,
    lat: 39.8,
  }),
  createStand({
    id: "willow-ridge",
    name: "Willow Ridge",
    treeType: "Black Willow",
    canopyDensity: 0.63,
    ageClass: "Early Mature",
    health: "Healthy",
    summary: "A flexible riparian stand with strong wetland function and layered shrubs.",
    management: "Maintain floodplain connectivity and remove invasive recruits.",
    lon: -97.4,
    lat: 35.2,
  }),
];
